AWSTemplateFormatVersion: '2010-09-09'
Description: "This stack deploys the bucket for seed-farmer projects in each account/region"
Parameters:
  ProjectName:
    Type: String
    Description: The name of the project
  BucketName:
    Type: String
    Description: The name of the Bucket
    MaxLength: 64
Resources:
  AccessLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}-access-logs'
      Tags:
        - Key: seedfarmer-artifacts
          Value: !Sub 'seedfarmer-${ProjectName}'
        - Key: seedfarmer-project
          Value: !Sub '${ProjectName}'
        - Key: Purpose
          Value: 'Access Logs'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}'
      Tags:
        - Key: seedfarmer-artifacts
          Value: !Sub 'seedfarmer-${ProjectName}'
        - Key: seedfarmer-project
          Value: !Sub '${ProjectName}'
      VersioningConfiguration:
        Status: Suspended
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref AccessLogsBucket
        LogFilePrefix: 'access-logs/'

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:*'
            Effect: Deny
            Resource:
              - !GetAtt 
                - Bucket
                - Arn
              - !Join 
                - ''
                - - !GetAtt 
                    - Bucket
                    - Arn
                  - /*
            Principal: '*'
            Condition:
              Bool:
                'aws:SecureTransport': "false"

Outputs:
  Bucket:
    Value: !Ref Bucket
    Export:
      Name: !Sub 'seedfarmer-${ProjectName}-${AWS::Region}-${AWS::AccountId}'
  AccessLogsBucket:
    Value: !Ref AccessLogsBucket
    Export:
      Name: !Sub 'seedfarmer-${ProjectName}-access-logs-${AWS::Region}-${AWS::AccountId}'
