AWSTemplateFormatVersion: '2010-09-09'
Description: "This stack deploys the bucket for seed-farmer projects in each account/region"
Parameters:
  ProjectName:
    Type: String
    Description: The name of the project
  BucketName:
    Type: String
    Description: The name of the Bucket
    MaxLength: 64
  AccessLoggingPrefix:
    Type: String
    Description: S3 key prefix for access logs
    Default: 'access-logs/'
  EnableSelfAccessLogs:
    Type: String
    Description: Enable S3 self access logging to access-logs/ prefix
    Default: "false"
    AllowedValues:
      - "true"
      - "false"

Conditions:
  SelfAccessLogsEnabled: !Equals 
    - !Ref EnableSelfAccessLogs
    - "true"

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}'
      Tags:
        - Key: seedfarmer-artifacts
          Value: !Sub 'seedfarmer-${ProjectName}'
        - Key: seedfarmer-project
          Value: !Sub '${ProjectName}'
      VersioningConfiguration:
        Status: Suspended
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration: !If
        - SelfAccessLogsEnabled
        - LogFilePrefix: !Ref AccessLoggingPrefix
        - !Ref "AWS::NoValue"

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:*'
            Effect: Deny
            Resource:
              - !GetAtt 
                - Bucket
                - Arn
              - !Join 
                - ''
                - - !GetAtt 
                    - Bucket
                    - Arn
                  - /*
            Principal: '*'
            Condition:
              Bool:
                'aws:SecureTransport': "false"
          - !If
            - SelfAccessLogsEnabled
            - Sid: S3ServerAccessLogsPolicy
              Effect: Allow
              Principal:
                Service: logging.s3.amazonaws.com
              Action: s3:PutObject
              Resource: !Sub '${Bucket.Arn}/${AccessLoggingPrefix}*'
              Condition:
                StringEquals:
                  aws:SourceAccount: !Ref AWS::AccountId
                ArnLike:
                  aws:SourceArn: !GetAtt Bucket.Arn
            - !Ref "AWS::NoValue"

Outputs:
  Bucket:
    Value: !Ref Bucket
    Export:
      Name: !Sub 'seedfarmer-${ProjectName}-${AWS::Region}-${AWS::AccountId}'