version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    - pip install uv
    - uv sync --group docs --frozen
    - uv run mkdocs build --strict

mkdocs:
  configuration: mkdocs.yml