name: examples
toolchainRegion: us-west-2
groups:
  - name: optionals
    path: manifests-multi/examples/optional-modules.yaml
  - name: optionals-2
    path: manifests-multi/examples/optional-modules-2.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: us-west-2
        default: true
      - region: us-east-2
  - alias: secondary
    accountId:
      valueFrom:
        envVariable: SECONDARY_ACCOUNT
    default: false
    regionMappings:
      - region: us-west-2
      - region: us-east-2
        default: true
