name: examples
toolchainRegion: us-west-2
groups:
  - name: optionals
    path: manifests/examples/optional-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: us-west-2
        default: true
      - region: us-east-2
