name: Check Documentation Dependencies

on:
  push:
    branches: 
      - "main"
    paths:
      - "docs/requirements-docs.txt"
      - ".readthedocs"
      - ".github/workflows/requirements-docs-test.yml"

  pull_request:
    branches:
      - "main"
      - "stable"
    paths:
      - "docs/requirements-docs.txt"
      - ".readthedocs"
      - ".github/workflows/requirements-docs-test.yml"

jobs:
  install:
    name: Install Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install Airflow and Dependencies
        run: pip install -r docs/requirements-docs.txt
